os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="sdl/2.0.4"
    - CONAN_USERNAME="chaosteil"
    - CONAN_CHANNEL="ci"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1

  matrix:
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE="chaosteil/conangcc48" CONAN_ARCHS="x86_64"
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE="chaosteil/conangcc48_32" CONAN_ARCHS="x86"
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE="chaosteil/conangcc49" CONAN_ARCHS="x86_64"
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE="chaosteil/conangcc49_32" CONAN_ARCHS="x86"
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE="chaosteil/conangcc52" CONAN_ARCHS="x86_64"
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE="chaosteil/conangcc52_32" CONAN_ARCHS="x86"
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE="chaosteil/conangcc53" CONAN_ARCHS="x86_64"
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE="chaosteil/conangcc53_32" CONAN_ARCHS="x86"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential make cmake autoconf automake xorg-dev libtool libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev libgl1-mesa-dev libesd0-dev libdbus-1-dev libudev-dev libgles1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libibus-1.0-dev

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
